services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" #default mqtt port
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw

  orch:
    image: frittenburger/wo-ist-dirk
    build: orch
    container_name: orch
    restart: unless-stopped
    ports:
      - "8884:8884" #http port wo-ist-dirk
    volumes:
      - ./orch/config:/app/config:rw
      - ./orch/data:/app/data:rw




