services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "8883:8883" #default mqtts port
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      # - /etc/letsencrypt:/mosquitto/letsencrypt:r
    restart: always

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
      - ./otrecorder/store:/store
      - ./otrecorder/config:/config
    restart: always

  owntracks-frontend:
    image: owntracks/frontend
    ports:
      - 8884:8884
    volumes:
      - ./frontend/config/config.js:/usr/share/nginx/html/config/config.js
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
      - LISTEN_PORT=8884
    restart: always

  file-logger:
    image: frittenburger/mqtt-file-logger
    volumes:
      - ./file-logger/config:/app/config:rw
      - ./file-logger/data:/app/data:rw
    restart: always




