services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    #container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" #default mqtt port
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
      - ./otrecorder/store:/store
      - ./otrecorder/config:/config
    restart: unless-stopped

  owntracks-frontend:
    image: owntracks/frontend
    ports:
      - 8884:8884
    volumes:
      - ./path/to/custom/config.js:/usr/share/nginx/html/config/config.js
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
      - LISTEN_PORT=8884
    restart: unless-stopped


